// Generated by CoffeeScript 1.7.1
var nestedObject;

nestedObject = {
  brother: {
    name: "Max",
    age: 11
  },
  sister: {
    name: "Ida",
    age: 9
  }
};

console.log(nestedObject.brother);

console.log(nestedObject.brother.name);

console.log(nestedObject);
