// Generated by CoffeeScript 1.7.1
var chaChaCha, clapsHands, date, friday, happy, knowsIt, mood, showIt, singing;

singing = true;

if (singing) {
  mood = "greatlyImproved";
}

happy = true;

knowsIt = true;

clapsHands = function() {
  return console.log("clapping hands");
};

chaChaCha = function() {
  return console.log("cha cha cha");
};

showIt = function() {
  return console.log("show it");
};

if (happy && knowsIt) {
  clapsHands();
  chaChaCha();
} else {
  showIt();
}

friday = false;

date = friday ? "sue" : "jill";

if (!false) {
  console.log("print if false");
}
