// Generated by CoffeeScript 1.7.1
var age, ages, countdown, eat, fastCountdown, filteredAges, food, name, num, yearsOld, _i, _len, _ref;

eat = function(food) {
  return console.log("eating " + food);
};

_ref = ['toast', 'cheese', 'wine'];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  food = _ref[_i];
  eat(food);
}

countdown = (function() {
  var _j, _results;
  _results = [];
  for (num = _j = 10; _j >= 1; num = --_j) {
    _results.push(num);
  }
  return _results;
})();

console.log("Count down: ", countdown);

fastCountdown = (function() {
  var _j, _results;
  _results = [];
  for (num = _j = 10; _j >= 1; num = _j += -2) {
    _results.push(num);
  }
  return _results;
})();

console.log("Fast count down: ", fastCountdown);

yearsOld = {
  "Max": 11,
  "Ida": 10,
  "Kelvin": 12
};

ages = (function() {
  var _results;
  _results = [];
  for (name in yearsOld) {
    age = yearsOld[name];
    _results.push(age);
  }
  return _results;
})();

console.log("Ages for JSON object: ", ages);

filteredAges = (function() {
  var _results;
  _results = [];
  for (name in yearsOld) {
    age = yearsOld[name];
    if (age > 10) {
      _results.push(name);
    }
  }
  return _results;
})();

console.log("Filtered ages: ", filteredAges);
