// Generated by CoffeeScript 1.7.1
var awardMedals, contenders,
  __slice = [].slice;

awardMedals = function() {
  var first, gold, others, rest, second, silver;
  first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
  gold = first;
  silver = second;
  rest = others;
  console.log(gold);
  console.log(silver);
  return console.log(rest);
};

contenders = ["Alice", "Bob", "Charlie", "Dennis", "Esther"];

awardMedals(contenders);
