// Generated by CoffeeScript 1.7.1
var lottery, _ref;

if (typeof a !== "undefined" && a !== null) {
  console.log("exists");
}

lottery = {
  drawWinner: function() {
    return {
      address: {
        zipcode: 5345
      }
    };
  }
};

console.log(typeof lottery.drawWinner === "function" ? (_ref = lottery.drawWinner().address) != null ? _ref.zipcode : void 0 : void 0);
